# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FoodyCat' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FoodyCat

  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'MOLH'
  pod 'Kingfisher'
  pod 'NVActivityIndicatorView/Extended'
  pod 'Localize-Swift'
  pod 'NotificationBannerSwift', '~> 3.0.0'
  pod 'IQKeyboardManagerSwift'
  pod 'iOSDropDown'
  pod 'AKSideMenu'
  pod 'TransitionButton'
  pod 'UITextView+Placeholder'
  pod 'Cosmos', '~> 23.0'
  pod 'RealmSwift', '~>10'
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'FSPagerView'
  pod 'OneSignalXCFramework', '>= 3.0.0', '< 4.0'
  pod 'ZendeskSupportSDK'

  post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end
  end

end

target 'OneSignalNotificationServiceExtension' do
  use_frameworks!
  #only copy below line
  pod 'OneSignalXCFramework', '>= 3.0.0', '< 4.0'
end
